### ISSUE TITLE
Trailing `]`

### ISSUE THREAD

**Issue by Leniorko** [DogeDark/dioxus-logger#1]
Is there any reason behind the trailing `]` symbol in logs format? Like at this line:
https://github.com/DogeDark/dioxus-logger/blob/0fb693114d02bd57adc2d81feb584613d07e1854/src/lib.rs#L25

It's not critical, but strange when the message have trailing symbol.

**Comment by DogeDark** [comment]
They are not required. You can create any format you want with the different ``{VARIABLE}`` and everything else is decoration so to say.
