### ISSUE TITLE
Support Dioxus 0.5

### ISSUE THREAD

**Issue by marc2332** [DogeDark/dioxus-logger#3]

**Comment by DogeDark** [comment]
I'll probably look into this soon. I didn't realize 232+ projects are using it. Though I guess that should be expected as it's used in the Dioxus template.

Just needs switching to tracing. 🙂

**Comment by alper** [comment]
Will there be anything required here for Dioxus 0.6?

**Comment by DogeDark** [comment]
> Will there be anything required here for Dioxus 0.6?

Nope, though I may add logging support for mobile and release a 0.6 version of this. In Dioxus 0.7 this will probably be integrated into the Dioxus repository with plans for more advanced logging functionality.
