### ISSUE TITLE
logs from log crate are not shown

### ISSUE THREAD

**Issue by LuckyTurtleDev** [DogeDark/dioxus-logger#6]
Log created with the `log` crate are not shown at the logger.
Some crates, which are used as dependencies,  may use `log` instead of `trace`. This messages are not show dioxus-logger.

```rust
log::error!("halloooooooo?");
```

**Comment by DogeDark** [comment]
I seemed to have missed this - my bad. Dioxus logger has moved to the main Dioxus repository and this repository is being archived. I will recreate your feature request over there.
